# Generated by Django 5.0.4 on 2024-04-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_company_client_company_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='client',
            field=models.ManyToManyField(related_name='sources', to='main.client'),
        ),
    ]
