# Generated by Django 5.0.4 on 2024-04-15 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_source_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='source',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='main.source'),
            preserve_default=False,
        ),
    ]
