# Generated by Django 5.0.4 on 2024-04-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_story_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='client',
            field=models.ManyToManyField(related_name='stories_as_client', to='main.client'),
        ),
    ]
