# Generated by Django 5.0.4 on 2024-04-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_story_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='body_text',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.URLField(max_length=20000),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('name', 'url')},
        ),
    ]
