# Generated by Django 5.0.4 on 2024-04-16 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_story_body_text_alter_story_title_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set(),
        ),
    ]
