# Generated by Django 5.0.4 on 2024-04-18 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_source_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='client',
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company'),
        ),
        migrations.RemoveField(
            model_name='story',
            name='client',
        ),
        migrations.RemoveField(
            model_name='source',
            name='client',
        ),
        migrations.AddField(
            model_name='story',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.company'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='source',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='main.company'),
            preserve_default=False,
        ),
    ]
