# Generated by Django 5.0.4 on 2024-04-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_source_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('url', 'client')},
        ),
        migrations.AlterUniqueTogether(
            name='story',
            unique_together={('url', 'client')},
        ),
    ]
