# Generated by Django 5.0.4 on 2024-04-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_source_updated_by_alter_story_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='body_text',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.TextField(max_length=1000),
        ),
    ]
